/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppSettingsRouteRouteImport } from './routes/_authenticated/app/settings/route'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAdminConvitesIndexRouteImport } from './routes/_authenticated/admin/convites/index'
import { Route as AuthenticatedAdminUsuariosIndexRouteImport } from './routes/_authenticated/admin/usuarios/index'
import { Route as AuthenticatedAppCatalogoIndexRouteImport } from './routes/_authenticated/app/catalogo/index'
import { Route as AuthenticatedAppRotinaIndexRouteImport } from './routes/_authenticated/app/rotina/index'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/app/settings/index'
import { Route as AuthenticatedAppSettingsAccountRouteImport } from './routes/_authenticated/app/settings/account'
import { Route as AuthenticatedAppSettingsAppearanceRouteImport } from './routes/_authenticated/app/settings/appearance'
import { Route as AuthenticatedAppSettingsDisplayRouteImport } from './routes/_authenticated/app/settings/display'
import { Route as AuthenticatedAppSettingsEpicRouteImport } from './routes/_authenticated/app/settings/epic'
import { Route as AuthenticatedAppSettingsNotificationsRouteImport } from './routes/_authenticated/app/settings/notifications'
import { Route as AuthenticatedAppSettingsSteamRouteImport } from './routes/_authenticated/app/settings/steam'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRouteRoute =
  AuthenticatedAppSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConvitesIndexRoute =
  AuthenticatedAdminConvitesIndexRouteImport.update({
    id: '/convites/',
    path: '/convites/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosIndexRoute =
  AuthenticatedAdminUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppCatalogoIndexRoute =
  AuthenticatedAppCatalogoIndexRouteImport.update({
    id: '/catalogo/',
    path: '/catalogo/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRotinaIndexRoute =
  AuthenticatedAppRotinaIndexRouteImport.update({
    id: '/rotina/',
    path: '/rotina/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppSettingsAccountRoute =
  AuthenticatedAppSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppSettingsAppearanceRoute =
  AuthenticatedAppSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppSettingsDisplayRoute =
  AuthenticatedAppSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppSettingsEpicRoute =
  AuthenticatedAppSettingsEpicRouteImport.update({
    id: '/epic',
    path: '/epic',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppSettingsNotificationsRoute =
  AuthenticatedAppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)
const AuthenticatedAppSettingsSteamRoute =
  AuthenticatedAppSettingsSteamRouteImport.update({
    id: '/steam',
    path: '/steam',
    getParentRoute: () => AuthenticatedAppSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/app/settings': typeof AuthenticatedAppSettingsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/app/settings/appearance': typeof AuthenticatedAppSettingsAppearanceRoute
  '/app/settings/display': typeof AuthenticatedAppSettingsDisplayRoute
  '/app/settings/epic': typeof AuthenticatedAppSettingsEpicRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/steam': typeof AuthenticatedAppSettingsSteamRoute
  '/admin/convites/': typeof AuthenticatedAdminConvitesIndexRoute
  '/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/app/catalogo/': typeof AuthenticatedAppCatalogoIndexRoute
  '/app/rotina/': typeof AuthenticatedAppRotinaIndexRoute
  '/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/app/settings/appearance': typeof AuthenticatedAppSettingsAppearanceRoute
  '/app/settings/display': typeof AuthenticatedAppSettingsDisplayRoute
  '/app/settings/epic': typeof AuthenticatedAppSettingsEpicRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/steam': typeof AuthenticatedAppSettingsSteamRoute
  '/admin/convites': typeof AuthenticatedAdminConvitesIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosIndexRoute
  '/app/catalogo': typeof AuthenticatedAppCatalogoIndexRoute
  '/app/rotina': typeof AuthenticatedAppRotinaIndexRoute
  '/app/settings': typeof AuthenticatedAppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/_authenticated/app/settings/appearance': typeof AuthenticatedAppSettingsAppearanceRoute
  '/_authenticated/app/settings/display': typeof AuthenticatedAppSettingsDisplayRoute
  '/_authenticated/app/settings/epic': typeof AuthenticatedAppSettingsEpicRoute
  '/_authenticated/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/_authenticated/app/settings/steam': typeof AuthenticatedAppSettingsSteamRoute
  '/_authenticated/admin/convites/': typeof AuthenticatedAdminConvitesIndexRoute
  '/_authenticated/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/_authenticated/app/catalogo/': typeof AuthenticatedAppCatalogoIndexRoute
  '/_authenticated/app/rotina/': typeof AuthenticatedAppRotinaIndexRoute
  '/_authenticated/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/app/settings'
    | '/errors/$error'
    | '/admin/'
    | '/app/'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/display'
    | '/app/settings/epic'
    | '/app/settings/notifications'
    | '/app/settings/steam'
    | '/admin/convites/'
    | '/admin/usuarios/'
    | '/app/catalogo/'
    | '/app/rotina/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/admin'
    | '/app'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/display'
    | '/app/settings/epic'
    | '/app/settings/notifications'
    | '/app/settings/steam'
    | '/admin/convites'
    | '/admin/usuarios'
    | '/app/catalogo'
    | '/app/rotina'
    | '/app/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/app/settings'
    | '/_authenticated/errors/$error'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/app/settings/account'
    | '/_authenticated/app/settings/appearance'
    | '/_authenticated/app/settings/display'
    | '/_authenticated/app/settings/epic'
    | '/_authenticated/app/settings/notifications'
    | '/_authenticated/app/settings/steam'
    | '/_authenticated/admin/convites/'
    | '/_authenticated/admin/usuarios/'
    | '/_authenticated/app/catalogo/'
    | '/_authenticated/app/rotina/'
    | '/_authenticated/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/convites/': {
      id: '/_authenticated/admin/convites/'
      path: '/convites'
      fullPath: '/admin/convites/'
      preLoaderRoute: typeof AuthenticatedAdminConvitesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios/': {
      id: '/_authenticated/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/catalogo/': {
      id: '/_authenticated/app/catalogo/'
      path: '/catalogo'
      fullPath: '/app/catalogo/'
      preLoaderRoute: typeof AuthenticatedAppCatalogoIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/rotina/': {
      id: '/_authenticated/app/rotina/'
      path: '/rotina'
      fullPath: '/app/rotina/'
      preLoaderRoute: typeof AuthenticatedAppRotinaIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/': {
      id: '/_authenticated/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/app/settings/account': {
      id: '/_authenticated/app/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AuthenticatedAppSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/app/settings/appearance': {
      id: '/_authenticated/app/settings/appearance'
      path: '/appearance'
      fullPath: '/app/settings/appearance'
      preLoaderRoute: typeof AuthenticatedAppSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/app/settings/display': {
      id: '/_authenticated/app/settings/display'
      path: '/display'
      fullPath: '/app/settings/display'
      preLoaderRoute: typeof AuthenticatedAppSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/app/settings/epic': {
      id: '/_authenticated/app/settings/epic'
      path: '/epic'
      fullPath: '/app/settings/epic'
      preLoaderRoute: typeof AuthenticatedAppSettingsEpicRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/app/settings/notifications': {
      id: '/_authenticated/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAppSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
    '/_authenticated/app/settings/steam': {
      id: '/_authenticated/app/settings/steam'
      path: '/steam'
      fullPath: '/app/settings/steam'
      preLoaderRoute: typeof AuthenticatedAppSettingsSteamRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminConvitesIndexRoute: typeof AuthenticatedAdminConvitesIndexRoute
  AuthenticatedAdminUsuariosIndexRoute: typeof AuthenticatedAdminUsuariosIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminConvitesIndexRoute: AuthenticatedAdminConvitesIndexRoute,
    AuthenticatedAdminUsuariosIndexRoute: AuthenticatedAdminUsuariosIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppSettingsRouteRouteChildren {
  AuthenticatedAppSettingsAccountRoute: typeof AuthenticatedAppSettingsAccountRoute
  AuthenticatedAppSettingsAppearanceRoute: typeof AuthenticatedAppSettingsAppearanceRoute
  AuthenticatedAppSettingsDisplayRoute: typeof AuthenticatedAppSettingsDisplayRoute
  AuthenticatedAppSettingsEpicRoute: typeof AuthenticatedAppSettingsEpicRoute
  AuthenticatedAppSettingsNotificationsRoute: typeof AuthenticatedAppSettingsNotificationsRoute
  AuthenticatedAppSettingsSteamRoute: typeof AuthenticatedAppSettingsSteamRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
}

const AuthenticatedAppSettingsRouteRouteChildren: AuthenticatedAppSettingsRouteRouteChildren =
  {
    AuthenticatedAppSettingsAccountRoute: AuthenticatedAppSettingsAccountRoute,
    AuthenticatedAppSettingsAppearanceRoute:
      AuthenticatedAppSettingsAppearanceRoute,
    AuthenticatedAppSettingsDisplayRoute: AuthenticatedAppSettingsDisplayRoute,
    AuthenticatedAppSettingsEpicRoute: AuthenticatedAppSettingsEpicRoute,
    AuthenticatedAppSettingsNotificationsRoute:
      AuthenticatedAppSettingsNotificationsRoute,
    AuthenticatedAppSettingsSteamRoute: AuthenticatedAppSettingsSteamRoute,
    AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  }

const AuthenticatedAppSettingsRouteRouteWithChildren =
  AuthenticatedAppSettingsRouteRoute._addFileChildren(
    AuthenticatedAppSettingsRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppSettingsRouteRoute: typeof AuthenticatedAppSettingsRouteRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCatalogoIndexRoute: typeof AuthenticatedAppCatalogoIndexRoute
  AuthenticatedAppRotinaIndexRoute: typeof AuthenticatedAppRotinaIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppSettingsRouteRoute:
    AuthenticatedAppSettingsRouteRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCatalogoIndexRoute: AuthenticatedAppCatalogoIndexRoute,
  AuthenticatedAppRotinaIndexRoute: AuthenticatedAppRotinaIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
